### ISSUE TITLE
heroku已经封禁了这个项目

### ISSUE THREAD

**Issue by Dimitri2020007** [mixool/xrayku#14]
fork项目再改名已经没用了，Create app直接报错。提示由于源代码违反了 Salesforce 可接受使用和面向外部的服务策略，我们无法部署您的应用。

**Comment by ldj-network** [comment]
- [ ] 以前部署的还能使用~

**Comment by Dimitri2020007** [comment]
> * [ ]  以前部署的还能使用~

现在再试试吧，我2天前部署这个项目的时候出现提示由于源代码违反了 Salesforce 可接受使用和面向外部的服务策略，我们无法部署您的应用。

**Comment by mixool** [comment]
fork 过后还要修改 部署按钮等地址

**Comment by Dimitri2020007** [comment]
修改部署按钮和地址是无效的
