### ISSUE TITLE
原版本已可用，可试着滚回原版本

### ISSUE THREAD

**Issue by DaoChen6** [mixool/xrayku#33]

**Comment by Dimitri2020007** [comment]
原版本是什么意思？指的是哪方面的？

**Comment by jiuture** [comment]
最终卡在最后一步，是什么原因呢？

2021/08/22 23:10:34 [INFO] Skipping cleanup as requested; leaving folder intact: /tmp/buildenv_2021-08-22-2305.387770092

**Comment by Dimitri2020007** [comment]
> 最终卡在最后一步，是什么原因呢？
> 
> 2021/08/22 23:18:31 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /usr/bin/caddy -ldflags -w -s -trimpath

这个是网页反应速度慢了，因为多了一个预编译caddy的环节。只要build complete出现刷新下网页就可以了。

**Comment by GitHub8192** [comment]
改完用戶名以及專案名稱後可以正常部署，反代也能通，可使用中卻通不了網，google都訪問不了。

**Comment by Dimitri2020007** [comment]
> 改完用戶名以及專案名稱後可以正常部署，反代也能通，可使用中卻通不了網，google都訪問不了。

仔细检查客户端与服务端的uuid和path是否一致

一致就能连通

**Comment by GitHub8192** [comment]
我已經三次進行部署了，結果都是一樣的，uuid'path都檢查過了。

**Comment by rtwinker** [comment]
uuid不太会出错，path是：/uuid-ss或者/uuid-vless等，根据协议不同而不同。

**Comment by 1804238643** [comment]
> 原版本是什么意思？指的是什么方面的？



> > 改完用戶名以及專案名稱後可以正常部署，反代也能通，可使用中卻通不了網，google都訪問不了。
> 
> 仔细检查客户端与服务端的uuid和path是否一致
> 
> 一致就能连通
还是连通不了

**Comment by 1804238643** [comment]
还是连通不了

**Comment by Dimitri2020007** [comment]
> 我已經三次進行部署了，結果都是一樣的，uuid'path都檢查過了。

自己看看xray.json的path怎么写的

还有caddyfile

**Comment by rtwinker** [comment]
好像是不行，wss出错：

**Comment by waynegan** [comment]
> > 我已經三次進行部署了，結果都是一樣的，uuid'path都檢查過了。
> 
> 反代能连通说明cdn向服务端的方向是畅通的
> 
> 连不上是客户端的设置的问题
> 
> 回头看看xray.json的path怎么写的
> 
> 还有caddyfile

2021-08-23T07:20:05.081521+00:00 app[web.1]: {"level":"error","ts":1629703205.081474,"logger":"http.log.error","msg":"dial unix /etc/caddy/vmess: connect: no such file or directory","request":{"remote_addr":"10.1.4.197:26552","proto":"HTTP/1.1","method":"GET","host":"wayne.herokuapp.com","uri":"/438af037-b328-4098-b435-e9b4fcf03569-vmess","headers":{"Cdn-Loop":["cloudflare; subreqs=1"],"X-Forwarded-Port":["443"],"Total-Route-Time":["0"],"Sec-Websocket-Key":["EKm2ldDoXDivjK6rEAEfng=="],"X-Forwarded-Proto":["https"],"Cf-Ew-Via":["15"]

自认为填的都对，请问我这个是什么问题？  502报错 "dial unix /etc/caddy/vmess: connect: no such file or directory"

**Comment by Dimitri2020007** [comment]
> > > 我已經三次進行部署了，結果都是一樣的，uuid'path都檢查過了。
> > 
> > 
> > 反代能连通说明cdn向服务端的方向是畅通的
> > 连不上是客户端的设置的问题
> > 回头看看xray.json的path怎么写的
> > 还有caddyfile
> 
> 2021-08-23T07:20:05.081521+00:00 app[web.1]: {"level":"error","ts":1629703205.081474,"logger":"http.log.error","msg":"dial unix /etc/caddy/vmess: connect: no such file or directory","request":{"remote_addr":"10.1.4.197:26552","proto":"HTTP/1.1","method":"GET","host":"wayne.herokuapp.com","uri":"/438af037-b328-4098-b435-e9b4fcf03569-vmess","headers":{"Cdn-Loop":["cloudflare; subreqs=1"],"X-Forwarded-Port":["443"],"Total-Route-Time":["0"],"Sec-Websocket-Key":["EKm2ldDoXDivjK6rEAEfng=="],"X-Forwarded-Proto":["https"],"Cf-Ew-Via":["15"]
> 
> 自认为填的都对，请问我这个是什么问题？ 502报错 "dial unix /etc/caddy/vmess: connect: no such file or directory"

你是不是改了v2的配置然后没有改caddy的反代配置?

**Comment by Dimitri2020007** [comment]
@waynegan 你fo了我的项目能连接吗？

**Comment by daxiaojiul** [comment]
> 
> 
> @waynegan 你fo了我的项目能连接吗？

请问是您的那个项目呀？  我部署了多次能正常跳转网页，就是在客户端里配置后无法联网

**Comment by waynegan** [comment]
> @waynegan 你fo了我的项目能连接吗？

你的VLESS专用的那个可以，其他的没成功，因为我不确定设立服务端时复制AUUID的时候是否带了空格。也不知道在Var config下直接更改能否生效（比如文件夹名会不会同步更改），我需要重新部署一遍试一下。

**Comment by daxiaojiul** [comment]
> 
> 
> > @waynegan  你fo了我的项目能连接吗？
> 
> 你的VLESS专用的那个可以，其他的没成功，因为我不确定设立服务端时复制AUUID的时候是否带了空格。也不知道在Var config下直接更改能否生效（比如文件夹名会不会同步更改），我需要重新部署一遍试一下。

期待能解决呀，我的始终无法联网

**Comment by Dimitri2020007** [comment]
> > @waynegan 你fo了我的项目能连接吗？
> 
> 请问是您的那个项目呀？ 我部署了多次能正常跳转网页，就是在客户端里配置后无法联网

我的vless专用项目，如果初次卡壳那就删了再试一次。

我在验证ws反代头处理

**Comment by Dimitri2020007** [comment]
不要fo我的同名项目，已经被heroku ban了。
错误已经修复了，可以重新fo这个项目运行了。
