### ISSUE TITLE
改好参数，部署出错

### ISSUE THREAD

**Issue by jgsports** [mixool/xrayku#34]
fork大佬的项目，部署时也改好了参数，出现We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by rtwinker** [comment]
fork后自己的readme里面要改成自己的项目名称，仔细看readme，现在貌似还有问题，等大佬澄清后再fork。

**Comment by DaoChen6** [comment]
改app.json里面的名称

**Comment by gentlelion99** [comment]
> 改app.json里面的名称

挺复杂的现在，没有基础怎么办

**Comment by gentlelion99** [comment]
> fork大佬的项目，部署时也改好了参数，出现We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

这个容器商也真是小气巴拉，薅点羊毛就这么抓狂

**Comment by DaoChen6** [comment]
`"name": "xrayku",`里把xrayku这个名改了

**Comment by DaoChen6** [comment]
部署完也连不上，不知道啥问题呢

**Comment by Dimitri2020007** [comment]
> 部署完也连不上，不知道啥问题呢

部署能过吗？

如果部署能过，能否连上？

部署后的容器日志发过来看下，还有客户端的。

**Comment by waynegan** [comment]
> > 部署完也连不上，不知道啥问题呢
> 
> 部署能过吗？
> 
> 如果部署能过，能否连上？
> 
> 部署后的容器日志发过来看下，还有客户端的。
> 
> 不要fo我的同名项目，已经确认被heroku给ban掉了。

还是502，这次我看了下日志，觉得有问题的在这些位置
2021-08-23T09:12:21.815393+00:00 app[web.1]: ls: /usr/share/caddy/61bfaf72-30a1-42d0-b9eb-cfe99db12506: No such file or directory
2021-08-23T09:12:21.815820+00:00 app[web.1]: /start.sh: line 18: ./v2ray: Permission denied
2021-08-23T09:12:22.122833+00:00 app[web.1]: {"level":"warn","ts":1629709942.122784,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":8}
logger":"http.log.error","msg":"dial unix /etc/caddy/vless: connect: no such file or directory"
"status":502,"err_id":"zq0qst4na","err_trace":"reverseproxy.statusError (reverseproxy.go:857)"}
我觉得是Caddy文件目录结构出现问题导致反代找不到位置，可能是在初始化过程中的Bug，或者其他的一些问题。

**Comment by Dimitri2020007** [comment]
这是初始化的bug。
heroku在目录中限制了权限。
所以写入根目录的文件不能执行。

**Comment by Dimitri2020007** [comment]
@waynegan 麻烦你重新fo一下这个项目测试下。

已经更改了执行路径

**Comment by waynegan** [comment]
> @waynegan 麻烦你重新fo一下这个项目测试下。
> 
> 已经更改了执行路径
> 
> 能继续用就给xdm说一声

我已经在fork里面的改了，加了行 chmod +x ./v2ray ./v2ctl，可以用了，终究还是权限的问题。
你改的应该没问题的，你Vless的那个项目这么写都没问题。

**Comment by Dimitri2020007** [comment]
> > @waynegan 麻烦你重新fo一下这个项目测试下。
> > 已经更改了执行路径
> > 能继续用就给xdm说一声
> 
> 我已经在fork里面的改了，加了行 chmod +x ./v2ray ./v2ctl，可以用了，终究还是权限的问题。
> 你改的应该没问题的，你Vless的那个项目这么写都没问题。

谢了

**Comment by DaoChen6** [comment]
> > > @waynegan 麻烦你重新fo一下这个项目测试下。
> > > 已经更改了执行路径
> > > 能继续用就给xdm说一声
> > 
> > 
> > 我已经在fork里面的改了，加了行 chmod +x ./v2ray ./v2ctl，可以用了，终究还是权限的问题。
> > 你改的应该没问题的，你Vless的那个项目这么写都没问题。
> 
> 谢了，我已经改过v2的下载和执行路径了，现在再部署应该没有问题了。各位可以重新fo一下这个项目了。
> 不要fo我的同名项目，已经被heroku ban了。

还是不行，建议滚回一个多小时前的加上chmod +x ./v2ray ./v2ctl

**Comment by Dimitri2020007** [comment]
> > > > @waynegan 麻烦你重新fo一下这个项目测试下。
> > > > 已经更改了执行路径
> > > > 能继续用就给xdm说一声
> > > 
> > > 
> > > 我已经在fork里面的改了，加了行 chmod +x ./v2ray ./v2ctl，可以用了，终究还是权限的问题。
> > > 你改的应该没问题的，你Vless的那个项目这么写都没问题。
> > 
> > 
> > 谢了，我已经改过v2的下载和执行路径了，现在再部署应该没有问题了。各位可以重新fo一下这个项目了。
> > 不要fo我的同名项目，已经被heroku ban了。
> 
> 还是不行，建议滚回一个多小时前的加上chmod +x ./v2ray ./v2ctl

你部署的是这个项目吗？
不要fo我的同名项目

如果还是出错把日志提供下。

**Comment by BIGIVAN** [comment]
> @DaoChen6 重新fo再试一次。
> 
> 若出错提供下日志

不行，还是部署不了

**Comment by BIGIVAN** [comment]
> @DaoChen6 重新fo再试一次。
> 
> 若出错提供下日志

Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by davoola** [comment]
> > @DaoChen6重佛再试一次。
> > 如果出错提供下日志
> 
> 无法创建项目：
> 我们无法部署您的应用程序，因为源代码违反了 Salesforce 可接受使用和面向外部的服务政策。

刚刚重新fork， README.md和app.json文件都做相应修改了。还是不行，跟你的错误一样

**Comment by davoola** [comment]
> > @DaoChen6重佛再试一次。
> > 如果出错了下
> 
> 无法创建项目：
> 我们无法部署您的应用程序，因为源代码违反了 Salesforce 可能使用和内部外部的服务政策。

刚刚fork，README.MD和app.json文件都修改了，还是不行，跟您的错误一样。

**Comment by Dimitri2020007** [comment]
@davoola 项目已经被ban了。试下别的项目吧。

**Comment by Dimitri2020007** [comment]
@BIGIVAN 项目被ban了，试别的项目吧。

**Comment by DaoChen6** [comment]
https://github.com/DaoChen6/IF-XTW

**Comment by Dimitri2020007** [comment]
> https://github.com/DaoChen6/IF-XTW

把你新代码的tor去掉。以免成为heroku封禁的下个目标。

**Comment by DaoChen6** [comment]
应该不是这个原因吧，可能是deploy的人多才会这样

**Comment by jgsports** [comment]
部署了https://github.com/DaoChen6/IF-XTW的fork版本，只改了deploy按钮的地址和uuid，成功 ！

**Comment by BIGIVAN** [comment]
> > https://github.com/DaoChen6/IF-XTW
> 
> 把你新代码的tor去掉。以免成为heroku封禁的下个目标。

这个可以用

**Comment by d1f2** [comment]
> [https://github.com/DaoChen6/IF-XTW ](https://github.com/DaoChen6/IF-XTW)

这个可以用

**Comment by DaoChen6** [comment]
[Heroku-v2ray](https://github.com/DaoChen6/Heroku-v2ray)这个也一样

**Comment by davoola** [comment]
> https://github.com/DaoChen6/IF-XTW

这个可以用，修改README.MD和app.json即可。谢谢

**Comment by BIGIVAN** [comment]
> [Heroku-v2ray](https://github.com/DaoChen6/Heroku-v2ray)这个也一样

又扑街了。。。全部失效

**Comment by davoola** [comment]
> > [Heroku-v2ray](https://github.com/DaoChen6/Heroku-v2ray)这个也一样
> 
> 又扑街了。。。全部失效

https://github.com/DaoChen6/IF-XTW 这个还是可以用的呀
