### ISSUE TITLE
给诸位发issue的提醒

### ISSUE THREAD

**Issue by Dimitri2020007** [mixool/xrayku#35]
1、We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
出现这个提示请删除此项目，放弃尝试。项目已经被ban。请出门右转。

2、如果出错请附上部署或运行的日志。没有日志就提问的直接关闭处理。

**Comment by gentlelion99** [comment]
> 1、We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
> 出现这个提示请删除此项目，放弃尝试。项目已经被ban。请出门右转。
> 
> 2、如果出错请附上部署或运行的日志。没有日志就提问的直接关闭处理。
> 
> 3、提问之前请善于搜索已有的issue，已有的issue与自己遇到的情况不符合可忽略这条。

这个项目有考虑重构吗 没得用好惨啊
