### ISSUE TITLE
没办法使用

### ISSUE THREAD

**Issue by ckhis-droid** [mixool/xrayku#36]
这个项目还在修改吗？为什么能搭建，但是没办法使用呢？

**Comment by Dimitri2020007** [comment]
是连不上还是其他的问题？

**Comment by gentlelion99** [comment]
> 是连不上还是其他的问题

有考虑重构这个项目吗

**Comment by Dimitri2020007** [comment]
> > 是连不上还是其他的问题
> 
> 有考虑重构这个项目吗

由于项目已被heroku ban掉，已经放弃维护。
