### ISSUE TITLE
客户端无法连接

### ISSUE THREAD

**Issue by daxiaojiul** [mixool/xrayku#39]
部署的Heroku应用能正常跳转网页，但是客户端无法联网。
2021/09/06 16:17:53 [Warning] [71082666] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.19.74.255/ffd3cbc4-4e2e-4824-8579-abeca194e298-vmess): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed

**Comment by zhangzhanqiu** [comment]
我也是按步骤安装好了，就是用不了。

**Comment by Dimitri2020007** [comment]
vless能连接上吗？
