### ISSUE TITLE
重新部署测试了，客户端还是不通

### ISSUE THREAD

**Issue by daxiaojiul** [mixool/xrayku#41]
我又重新部署应用尝试了，在客户端还是不能联网。大佬，能否给解决一下。
2021/09/07 21:12:50 [Warning] [3538630400] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (f7e1-vless): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed

**Comment by Dimitri2020007** [comment]
你试下这个项目

https://github.com/DaoChen6/IF-XTW.git

或者我的
