### ISSUE TITLE
新版的vless如何部署？

### ISSUE THREAD

**Issue by xiaoming140** [mixool/xrayku#6]
![vless](https://user-images.githubusercontent.com/64464497/107355736-de65f180-6b0a-11eb-8648-5ef9c8b00495.png)
##这个流控怎么填还有其他参数呢。

###log:

    [VLESS] xray123(104***83:443)
启动服务(2021/2/9 19:15:43)...
V2Ray 4.31.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.2 windows/386)
A unified platform for anti-censorship.
main: failed to read config files: [stdin:] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  stdin:
v2ray.com/core/infra/conf: XTLS only supports TCP, mKCP and DomainSocket for now. > exit status -1

**Comment by mixool** [comment]
不支持xtls
